name: tescsiprt_fan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-12.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  firebase_auth: 3.6.1
  email_validator: 2.1.16
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.7
  form_field_validator: 1.1.0
  equatable: 2.0.3
  cloud_firestore: 3.4.2
  dio: 4.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

